config/routes.rb
Rails.application.routes.draw do
  
  get  'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :accountabilities, except: [:show]
    resources :admins, except: [:show]
    resources :events , except: [:show]
    resources  :positions
    get 'dashboard', to:'dashboard#index'
 end
  
  namespace :site do
    get 'home/index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # O trecho método abaixo representa o scopo acima 
  # def self.with_full_access
    # where(role: 'full_access')
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :description, :name

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/position.rb
class Position < ApplicationRecord
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
  	else
  		"aplication"
  	end		   	
  end 
end

app/controllers/backoffice/accountabilities_controller.rb
class Backoffice::AccountabilitiesController < BackofficeController 
  def index
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
 before_action :set_admin, only: [:edit,:update, :destroy]
  
  def index
    @admins = Admin.all
    #@admins = Admin.where(role: 'full_access')
    
    #Vindo através do scope
    #@admins = Admin.with_full_access
  end

  def new
    @admin = Admin.new
  end

  def create  
    @admin = Admin.new(params_admin)
    if @admin.save
        redirect_to backoffice_admins_path, notice: "O cargo (#{@admin.email}) foi cadastrado com sucesso!"
    else
      render :new
    end  
  end 

  def edit
    
  end
  
  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end  


    if @admin.update (params_admin)
      redirect_to backoffice_admins_path, notice: "O cargo (#{@admin.email}) foi atualizado com sucesso!"
    else
      render :edit
    end  
  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O cargo (#{@admin.email}) foi excluído com sucesso!"
    else
      render :index
    end  
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end
  

  def params_admin
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end 
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  
  
  def index
  end
end

app/controllers/backoffice/events_controller.rb
class Backoffice::EventsController < BackofficeController 
  before_action :set_event, only: [:edit,:update]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create  
    @event = Event.new(params_event)
    if @event.save
        redirect_to backoffice_events_path, notice: "O evento (#{@event.name}) foi cadastrado com sucesso!"
    else
      render :new
    end  
  end 

  def edit
    
  end

  def update
    if @event.update (params_event)
      redirect_to backoffice_event_path, notice: "O evento (#{@event.name}) foi atualizado com sucesso!"
    else
      render :edit
    end  
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def params_event
    params.require(:event).permit(:name, :description, :date_event, :avatar)
  end 
end

app/controllers/backoffice/positions_controller.rb
class Backoffice::PositionsController < BackofficeController
  before_action :set_position, only: [:edit,:update]
  
  def index
    @positions = Position.all
  end

  def new
  	@position = Position.new
  end

  def create	
    @position = PositionService.create(params_position)
    
    #Se não existir erros
    unless @position.errors.any?
       redirect_to backoffice_positions_path, notice: "O cargo (#{@position.description}) foi cadastrado com sucesso!"
    else
      render :new
    end  
  end	

  def edit
    
  end
  
  def update
  	if @position.update	(params_position)
      redirect_to backoffice_positions_path, notice: "O cargo (#{@position.description}) foi atualizado com sucesso!"
    else
      render :edit
    end  
  end

  private

  def set_position
    @position = Position.find(params[:id])
  end
  

  def params_position
    params.require(:position).permit(:description)
  end	
end

app/controllers/backoffice/positions_controller/position_service.rb
class Backoffice::PositionsController::PositionService
  attr_accessor :position

  def self.create(params_position)
    @position = Position.new(params_position)

    if @position.valid?
      @position.save!
    end  
    @position        
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  
  layout "backoffice"
end  

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/accountabilities_helper.rb
module Backoffice::AccountabilitiesHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/events_helper.rb
module Backoffice::EventsHelper
end

app/helpers/backoffice/positions_helper.rb
module Backoffice::PositionsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backoffice/accountabilities/index.html.erb
<h1>Backoffice::Accountabilities#index</h1>
<p>Find me in app/views/backoffice/accountabilities/index.html.erb</p>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", 
           locals: {action: "Editando Administrador"} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>
 
  <div class="panel panel-default">
        <div class="panel-heading">
            Listando Administradores
            <%= link_to new_backoffice_admin_path, class:"btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
                <i class="fa fa-plus"></i>
            <% end %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Tipo de Acesso</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    
                        <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.email %></td>
                            <td><%= admin.role_i18n %></td>
                            <td style="width: 150px">
                                <%= link_to edit_backoffice_admin_path(admin.id), class:"btn btn-primary btn-circle" do %>
                                    <i class="fa fa-times"></i>
                                <% end %>
                                <% if current_admin.id != admin.id %>
                                     <%= link_to backoffice_admin_path(admin), method: :delete,
                                         class:"btn btn-danger btn-circle", data: {confirm:
                                            t('messages.confirm_with', item: admin.name)}  do %>     
                                        <i class="fa fa-minus"> </i>
                                     <% end %> 
                                <% end %> 
                            </td> 
                          </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
   </div>
 

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", 
           locals: {action: "Novo Administrador"} %>

app/views/backoffice/dashboard/index.html.erb
 
<h1 class="page-header">Dashboard</h1>

                 

app/views/backoffice/events/shared/_form.html.erb
<h1 class="page-header">Eventos</h1>
<% if @event.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li> <%= message %></li>
          <% end %>   
          </ul>
                  
         </div>
   <% end %>
  

<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="col-lg-12">
        <%= form_for ([:backoffice, @event]) do |f| %>
            <div class="form-group col-lg-6">
                <label>Nome evento</label>
                <%= f.text_field :name, class:"form-control", placeholder:"Ex: Evento" %>
                <br>
                <label>Imagem do evento</label>
                 <%= f.file_field :avatar %>
            </div>
            <div class="form-group col-lg-6">
                <label>Descrição</label>
                <%= f.text_area :description, class:"form-control", rows:"6", placeholder:"Ex: Evento" %>
            </div>
            <div class="form-group col-lg-6">
                <label>Data do evento</label>
                <%= f.datetime_select :date_event, class:"form-control "%>
            </div>
            
            <button type="submit"  class="btn btn-success">Salvar</button> 
        <% end %>
       
      </div>  
    </div>
    <!-- /.panel-body -->
</div>

app/views/backoffice/positions/shared/_form.html.erb
  <h1 class="page-header">Cargos</h1>
  <% if @position.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
          <% @position.errors.full_messages.each do |message| %>
            <li> <%= message %></li>
          <% end %>   
          </ul>
                  
         </div>
   <% end %>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="col-lg-6">
        <%= form_for ([:backoffice, @position]) do |f| %>
            <div class="form-group">
                <label>Descrição</label>
                <%= f.text_field :description, class:"form-control", placeholder:"Ex: RH" %>
            </div>
            <button type="submit"  class="btn btn-success">Salvar</button> 
        <% end %>
      </div>  
    </div>
    <!-- /.panel-body -->
</div>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>