config/routes.rb
Rails.application.routes.draw do
  
  get  'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :accountabilities, except: [:show]
    resources :admins, except: [:show]
    resources :events , except: [:show]
    resources  :positions
    get 'dashboard', to:'dashboard#index'
 end
  
  namespace :site do
    get 'home/index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # O trecho método abaixo representa o scopo acima 
  # def self.with_full_access
    # where(role: 'full_access')
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :description, :name

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/position.rb
class Position < ApplicationRecord
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
  	else
  		"aplication"
  	end		   	
  end 
end

app/controllers/backoffice/accountabilities_controller.rb
class Backoffice::AccountabilitiesController < BackofficeController 
  def index
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
 before_action :set_admin, only: [:edit,:update, :destroy]
  
  def index
    @admins = Admin.all
    #@admins = Admin.where(role: 'full_access')
    
    #Vindo através do scope
    #@admins = Admin.with_full_access
  end

  def new
    @admin = Admin.new
  end

  def create  
    @admin = Admin.new(params_admin)
    if @admin.save
        redirect_to backoffice_admins_path, notice: "O cargo (#{@admin.email}) foi cadastrado com sucesso!"
    else
      render :new
    end  
  end 

  def edit
    
  end
  
  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end  


    if @admin.update (params_admin)
      redirect_to backoffice_admins_path, notice: "O cargo (#{@admin.email}) foi atualizado com sucesso!"
    else
      render :edit
    end  
  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O cargo (#{@admin.email}) foi excluído com sucesso!"
    else
      render :index
    end  
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end
  

  def params_admin
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end 
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  
  
  def index
  end
end

app/controllers/backoffice/events_controller.rb
class Backoffice::EventsController < BackofficeController 
  before_action :set_event, only: [:edit,:update]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create  
    @event = Event.new(params_event)
    if @event.save
        redirect_to backoffice_events_path, notice: "O evento (#{@event.name}) foi cadastrado com sucesso!"
    else
      render :new
    end  
  end 

  def edit
    
  end

  def update
    if @event.update (params_event)
      redirect_to backoffice_event_path, notice: "O evento (#{@event.name}) foi atualizado com sucesso!"
    else
      render :edit
    end  
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def params_event
    params.require(:event).permit(:name, :description, :date_event, :avatar)
  end 
end

app/controllers/backoffice/positions_controller.rb
class Backoffice::PositionsController < BackofficeController
  before_action :set_position, only: [:edit,:update]
  
  def index
    @positions = Position.all
  end

  def new
  	@position = Position.new
  end

  def create	
    @position = PositionService.create(params_position)
    
    #Se não existir erros
    unless @position.errors.any?
       redirect_to backoffice_positions_path, notice: "O cargo (#{@position.description}) foi cadastrado com sucesso!"
    else
      render :new
    end  
  end	

  def edit
    
  end
  
  def update
  	if @position.update	(params_position)
      redirect_to backoffice_positions_path, notice: "O cargo (#{@position.description}) foi atualizado com sucesso!"
    else
      render :edit
    end  
  end

  private

  def set_position
    @position = Position.find(params[:id])
  end
  

  def params_position
    params.require(:position).permit(:description)
  end	
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  
  layout "backoffice"
end  

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/accountabilities_helper.rb
module Backoffice::AccountabilitiesHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/events_helper.rb
module Backoffice::EventsHelper
end

app/helpers/backoffice/positions_helper.rb
module Backoffice::PositionsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
<% if @admin.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
          <% @admin.errors.full_messages.each do |message| %>
            <li> <%= message %></li>
          <% end %>   
          </ul>
                  
         </div>
   <% end %>
  

<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="col-lg-6">
        <%= form_for ([:backoffice, @admin]) do |f| %>
            <div class="form-group">
                <label>Nome do administrador</label>
                <%= f.text_field :name, class:"form-control", placeholder:"Ex: Nome" %>
            </div>      
       
            <div class="form-group">
                <label>E-mail administrador</label>
                <%= f.text_field :email, class:"form-control", placeholder:"Ex: E-mail" %>
            </div>

                       
             <div class="form-group ">
                    <%= f.label :password %>
                    <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>

             </div>
             
             <div class="form-group ">
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da senha" %>
             </div>
            
             <button type="submit"  class="btn btn-success">Salvar</button> 
             
        <% end %>
       
      </div>  
    </div>
    <!-- /.panel-body -->
</div>

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
      <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html">SB Admin v2.0</a>
          </div>
          <!-- /.navbar-header -->

          <ul class="nav navbar-top-links navbar-right">
          <li><%= current_admin.name %></li>
              <!-- /.dropdown -->
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-user">
                     <li>
                        <%= link_to destroy_admin_session_path, method: :delete do %>
                          <i class="fa fa-sign-out fa-fw"></i> 
                          Sair
                        <% end %>
                      </li>
                  </ul>
                  <!-- /.dropdown-user -->
              </li>
              <!-- /.dropdown -->
          </ul>
          <!-- /.navbar-top-links -->

          <div class="navbar-default sidebar" role="navigation">
              <div class="sidebar-nav navbar-collapse">
                  <ul class="nav" id="side-menu">
                      <li>
                      <%= link_to backoffice_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> Painel Administrativo</a>
                      <% end %>    
                      </li>

                      <li>
                         <%= link_to backoffice_positions_path do %>
                            <i class="fa fa-th-list fa-fw"></i> Cargos
                         <% end %>
                      </li>

                      <li>
                         <%= link_to backoffice_events_path do %>
                            <i class="fa  fa-bullhorn fa-fw"></i> Eventos
                         <% end %>
                      </li>
                      <li>
                         <%= link_to backoffice_accountabilities_path do %>
                            <i class="fa  fa-file fa-fw"></i> Contas
                         <% end %>
                      </li>

                      <li>
                         <%= link_to backoffice_admins_path do %>
                            <i class="fa  fa-users fa-fw"></i> Administradores
                         <% end %>
                      </li>
                        
                  </ul>
              </div>
              <!-- /.sidebar-collapse -->
          </div>
          <!-- /.navbar-static-side -->
      </nav>